### DISCUSSION TITLE
Go autoinstrumentation traces does not show endpoint path in Observability Backend

### DISCUSSION THREAD

**Discussion by carobaldino** [open-telemetry/opentelemetry-go#4647] [Q&A]
Hello!

I'm using [auto-instrumentation for Golang](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pkgs/container/opentelemetry-go-instrumentation%2Fautoinstrumentation-go) via k8s Otel Operator. 

I also use it for Node and Python. But Go is the only language that **does not shows the requests endpoint paths and duration in the traces in the observability backend**, it only shows the request method, but not the endpoint (I'm using Tempo in this example as observability backend, but I also tried with Jaeger). But then, If I open or inspect the trace, I can see all the values of duration and endpoints of the request:

- On the left, you can see how traces are shown when I send requests to different endpoints: service name and method are there but not the path of the endpoint.
- On the right, is all the data that is shown inside the traceid, but is not being shown in the overview of the Left.

![image](https://github.com/open-telemetry/opentelemetry-go/assets/22280206/34b5f0ec-f530-4857-87e9-06d3bb580f03)

On the other hand, this is how traces look like when using nodejs autointrumentation for instance (and is what I thought I was going to see with Golang too):

![image](https://github.com/open-telemetry/opentelemetry-go/assets/22280206/3f4de238-c3bd-43ee-85b6-b2affdf95af9)

I've been reading and I don't know if this could be related with some bug or with some misconfiguration on my side.

The Instrumentation CRD is configured as below:
```yaml
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://localhost:4317
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://localhost:4317/v1/traces
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://localhost:4317/v1/logs
      - name: OTEL_LOG_LEVEL
        value: error
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.7.0-alpha
    env:
      - name: OTEL_SERVICE_NAME
        value: "internal-it-go"
      - name: OTEL_GO_AUTO_TARGET_EXE
        value: "/app/main"
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://localhost:4317
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://localhost:4317
      - name: OTEL_LOG_LEVEL
        value: error
```

So my questions are:
- is there any env variable I should use apart from those to get the traces correctly in Tempo?
- are traces *actually* being shown "incomplete" in Tempo?, or in fact as the data inside the trace is complete, this is not really an issue?

Thank you!

C.
