### DISCUSSION TITLE
Filed 'SeverityText' is not mapped from field 'LogAttributes'

### DISCUSSION THREAD

**Discussion by Wudadada** [open-telemetry/opentelemetry-go#5902] [Q&A] [answered]
Is there any solutions to map LogAttributes to SeverityText?

![1](https://github.com/user-attachments/assets/8c2c3708-2cb4-4518-b3a3-4b21c57df15d)
![2](https://github.com/user-attachments/assets/989869ea-4fa2-4176-adce-d0708766234b)

my otel-col's config
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:19100']

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
  attributes:
    actions:
      - key: LogAttributes
        action: delete

exporters:
  clickhouse:
    endpoint: tcp://10.105.212.248:9000?dial_timeout=10s
    create_schema: true
    database: otel
    async_insert: true
    ttl: 72h
    compress: lz4
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    username: "default"
    password: "123"
    cluster_name: cluster_3S_1R
    table_engine:
      name: "ReplicatedMergeTree"

    logs_table_name: otel_logs

    traces_table_name: otel_traces

    metrics_tables:
      gauge: 
        name: "otel_metrics_gauge"
      sum: 
        name: "otel_metrics_sum"
      summary: 
        name: "otel_metrics_summary"
      histogram: 
        name: "otel_metrics_histogram"
      exponential_histogram: 
        name: "otel_metrics_exp_histogram"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [clickhouse]

  telemetry:
    logs:
      level: "debug"
```

my slog's handler
```
type TraceHandler struct {
	handler slog.Handler
}

func (h *TraceHandler) Enabled(ctx context.Context, level slog.Level) bool {
	return h.handler.Enabled(ctx, level)
}

func (h *TraceHandler) Handle(ctx context.Context, r slog.Record) error {
	spanContext := trace.SpanContextFromContext(ctx)
	if spanContext.IsValid() {
		r.AddAttrs(
			slog.String("TraceID", spanContext.TraceID().String()),
			slog.String("SpanID", spanContext.SpanID().String()),
		)
	}

	var severityText string
	switch r.Level {
	case slog.LevelDebug:
		severityText = "DEBUG"
	case slog.LevelInfo:
		severityText = "INFO"
	case slog.LevelWarn:
		severityText = "WARN"
	case slog.LevelError:
		severityText = "ERROR"
	default:
		severityText = "DEFAULT"
	}

	r.AddAttrs(slog.String("SeverityText", severityText))

	return h.handler.Handle(ctx, r)
}
```
