### ISSUE TITLE
Unable to export data from otel-collector to prometheus

### ISSUE THREAD

**Issue by Palit-Mukul** [open-telemetry/opentelemetry-go#1295]
I am trying to send metrics to otel-collector so that it could be exported to prometheus but am I getting the following logs in terminal.
```
otel-collector_1  | InstrumentationLibraryMetrics #0
otel-collector_1  | InstrumentationLibrary test-basic 
otel-collector_1  | Metric #0
otel-collector_1  | Descriptor:
otel-collector_1  |      -> Name: 
otel-collector_1  | hitsMeasure the total hits 
otel-collector_1  |      -> Description: 
otel-collector_1  |      -> Unit: 
otel-collector_1  | 
otel-collector_1  | labelA	chocolate
otel-collector_1  | 
otel-collector_1  | labelB	raspberry
otel-collector_1  | 
otel-collector_1  | labelCvanillaz=U�VsBV�VsB!@
otel-collector_1  |      -> DataType: None
```
I am unable to understand why these special symbols are coming
I am using OTEL version 0.13.0

**Comment by MrAlias** [comment]
@Palit-Mukul do you have a minimal example of code that can reproduce this?

**Comment by Palit-Mukul** [comment]
@MrAlias  This is the sample main function through which I am sending the metrics
```
func main() {
	exporter, err := otlp.NewExporter(
		otlp.WithInsecure(),
		otlp.WithAddress("0.0.0.0:55678"),
	)
	if err != nil {
		fmt.Println(err)
	}
	pusher := push.New(
		basic.New(
			simple.NewWithExactDistribution(),
			exporter,
		),
		exporter,
		push.WithPeriod(2*time.Second),
	)
	pusher.Start()
	defer pusher.Stop()
	global.SetMeterProvider(pusher.MeterProvider())

	global.SetTextMapPropagator(propagators.Baggage{})
	meter := global.Meter("test-basic")

	commonLabels := []label.KeyValue{
		label.String("labelA", "chocolate"),
		label.String("labelB", "raspberry"),
		label.String("labelC", "vanilla"),
	}

	counter := metric.Must(meter).NewFloat64Counter("hits",
		metric.WithDescription("Measure the total hits"))
	counter.Add(context.Background(), 5)
	counter1 := metric.Must(meter).NewInt64Counter("hit")
	ctx := context.Background()
	meter.RecordBatch(
		ctx,
		commonLabels,
		counter1.Measurement(1),
	)
}
```

**Comment by inge4pres** [comment]
> otlp.WithAddress("0.0.0.0:55678")

@Palit-Mukul this looks like a weird address...

**Comment by Palit-Mukul** [comment]
```
`version: "3.1"
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   
      - "8888:8888"   
      - "8889:8889" 
      - "55678:55678"       
      - "55680:55679"
  # Agent
  otel-agent:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777"   # pprof extension
      - "8887:8888"   # Prometheus metrics exposed by the agent
    depends_on:
      - otel-collector
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
```
This is the docker compose file which I am using and I have used 55678 for otel-collector. 
Below is the otel-collector config
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55678
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: [ '0.0.0.0:8889' ]

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: versionsvc

  logging:
    loglevel: debug

processors:
  batch:
  queued_retry:

service:
  pipelines:
    metrics:
      receivers: [otlp,prometheus]
      exporters: [logging,prometheus]
      processors: [batch, queued_retry]
```
`
