### ISSUE TITLE
When using Push(OTLP) and Pull (Prometheus) controller the error: `controller already started` is showing

### ISSUE THREAD

**Issue by yorikya** [open-telemetry/opentelemetry-go#1538]
**Describe the bug**
In our company, we are using opentelemetry-sdk-go to export the metrics from a service. We are setting the OTLP within Prometheus exporter as shown in the [example](https://github.com/open-telemetry/opentelemetry-go/tree/main/example/prom-collector). When service is starting run all metrics are flowing via OTLP exporter and available via Prometheus endpoint as well.
But when we are querying the Prometheus endpoint an error `controller already started` is showing. Seems everything is works as expected but the error is bordering us.

**Steps to reproduce**
1. Run an otelcollector on a host with the next config (`config.yaml`):
```
receivers:
  otlp/notls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [logging]
    
    traces:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [logging]    
```

2. Send a metric:
```
observerCallback := func(_ context.Context, result metric.Float64ObserverResult) {
		result.Observe(1, resources.NewLabels(map[string]interface{}{
			"db-instance": "Node",
		})...)
	}
	metric.Must(meterProvider).NewFloat64ValueObserver("create node", observerCallback)
```
3.  Now query the service Prometheus endpoint and check the metric:
```
curl localhost:8080/metrics
# HELP create_node_User
# TYPE create_node_User gauge
create_node_User{db_instance="Node"} 1
```

**What did you expect to see?**
Everything working as expected

**What did you see instead?**
I am see an error in the log
```
➜  afvisibilitytester git:(master) ✗ go run .                                          
2021/02/15 17:28:58 controller already started
```

**What version did you use?**
Version: `v0.17.0`

**Environment**
OS: ("Ubuntu 14.04", "MAC")
Compiler(if manually compiled): (go 1.14)

Why the error occurs, am I doing something wrong? Or the example is wrong? Or its a real bug?

**Additional context**
I found some [issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1207) Support both push and pull based metrics at the same time, but I am not sure if it related.
