### ISSUE TITLE
NewInt64Histogram Type ， collector output gauge

### ISSUE THREAD

**Issue by domyway** [open-telemetry/opentelemetry-go#2553]
main.go piece of code 
```
cont := controller.New(
		processor.NewFactory(
			simple.NewWithInexpensiveDistribution(),
			meterExporter,
		),

		append(opts, controller.WithExporter(meterExporter), controller.WithCollectPeriod(CollectPeriod))...,
	)
```

```
t, _ := meter.NewInt64Histogram("NewInt64Histogram_test")
t.Record(ctx, 1)
```
metrics export to collector:v0.40.0, the config.yaml 

```
exporters:
    prometheus:
        endpoint: "172.17.0.2:8889"
        namespace: promexample
        const_labels:
          label1: value1
        resource_to_telemetry_conversion:
          enabled: true
```

browse http://127.0.0.1:8889/metrics
output :
```
# HELP promexample_NewInt64Histogram_test 
# TYPE promexample_NewInt64Histogram_test gauge
promexample_NewInt64Histogram_test{label1="value1",service_name="this-is-my-app"} 1
```

I use NewInt64Histogram，why output the "# TYPE promexample_NewInt64Histogram_test gauge", it should be "# TYPE promexample_NewInt64Histogram_test histogram"
