### ISSUE TITLE
The metric target_info is generated with timestamp 1970-01-01T00:00:00Z  and how to disable it by WithoutTargetInfo

### ISSUE THREAD

**Issue by valdemarpavesi** [open-telemetry/opentelemetry-go#4133]
### Description

The metric target_info is generated with timestamp 1970-01-01T00:00:00Z 
How to disable it by WithoutTargetInfo?
```
22ts=2023-05-23T19:54:27.441403344Z caller=push.go:130 level=error user=test msg="push error" err="rpc error: code = Code(400) desc = failed pushing to ingester: user=test: the sample has been rejected because another sample with a more recent timestamp has already been ingested and this sample is beyond the out-of-order time window of 12h (err-mimir-sample-timestamp-too-old). The affected sample has timestamp 1970-01-01T00:00:00Z and is from series {__name__=\"target_info\", job=\"unknown_service:otel\", telemetry_sdk_language=\"go\", telemetry_sdk_name=\"opentelemetry\", telemetry_sdk_version=\"1.16.0\"}"
```

### Environment

- Go Version: go version go1.20.4 darwin/amd64
- opentelemetry-go version:  v1.16.0/v0.39.0

### Steps To Reproduce

code
```
package main

import (
	"context"
	"errors"
	"fmt"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
	api "go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/sdk/metric"
)

func main() {
	ctx := context.Background()

	exp, err := otlpmetrichttp.New(ctx)
	if err != nil {
		panic(err)
	}
	
	meterProvider := metric.NewMeterProvider(metric.WithReader(metric.NewPeriodicReader(exp)))
	defer func() {
		if err := meterProvider.Shutdown(ctx); err != nil {
			panic(err)
		}
	}()

	otel.SetMeterProvider(meterProvider)

	meter := meterProvider.Meter("benchSyncViews")

	opt := api.WithAttributes(
		attribute.Key("test").String("2"),
		attribute.Key("job").String("otel"))
	o := []api.AddOption{opt}

	counter, err := meter.Float64UpDownCounter("t-float64-counter")
	if err != nil {
		panic(err)
	}

	fmt.Println("start")

	//add metrics
	counter.Add(ctx, 1.0, o...)

	timer1 := time.NewTimer(5 * time.Second)
	<-timer1.C
	
}

```

### Expected behavior

Disable target_info and fix timestamp

**Comment by valdemarpavesi** [comment]
This msg is from Mimir, target_info been send to the final destination, it is otlp not prometheus.

 export OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:3333/otlp
 export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
 export OTEL_EXPORTER_OTLP_COMPRESSION=gzip
 
 how to disable target_info

**Comment by valdemarpavesi** [comment]
This code is based on example:

https://github.com/open-telemetry/opentelemetry-go/blob/ff9fa334c91983bf58e5abbe17e1aec7f5c5089e/exporters/otlp/otlpmetric/otlpmetrichttp/example_test.go

**Comment by pellared** [comment]
This is the only metric produced by the OTLP exporter:

```
{
   "resourceMetrics":[
      {
         "resource":{
            "attributes":[
               {
                  "key":"service.name",
                  "value":{
                     "stringValue":"unknown_service:go-playground"
                  }
               },
               {
                  "key":"telemetry.sdk.language",
                  "value":{
                     "stringValue":"go"
                  }
               },
               {
                  "key":"telemetry.sdk.name",
                  "value":{
                     "stringValue":"opentelemetry"
                  }
               },
               {
                  "key":"telemetry.sdk.version",
                  "value":{
                     "stringValue":"1.16.0"
                  }
               }
            ]
         },
         "scopeMetrics":[
            {
               "scope":{
                  "name":"benchSyncViews"
               },
               "metrics":[
                  {
                     "name":"t-float64-counter",
                     "sum":{
                        "dataPoints":[
                           {
                              "attributes":[
                                 {
                                    "key":"job",
                                    "value":{
                                       "stringValue":"otel"
                                    }
                                 },
                                 {
                                    "key":"test",
                                    "value":{
                                       "stringValue":"2"
                                    }
                                 }
                              ],
                              "startTimeUnixNano":"1685462609849888900",
                              "timeUnixNano":"1685462614854207600",
                              "asDouble":1
                           }
                        ],
                        "aggregationTemporality":2
                     }
                  }
               ]
            }
         ],
         "schemaUrl":"https://opentelemetry.io/schemas/1.17.0"
      }
   ]
}
```

[`target_info` is only used](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-go+%22target_info%22+&type=code) in Prometheus exporter](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/prometheus).

Please double-check your setup and feel free to provide better repro steps if you still face the issue.
Also consider that it might be a bug in Grafana Mimir.

**Comment by pellared** [comment]
Closing as stale.

**Comment by alexfalkowski** [comment]
Hello! 

I seem to be able to replicate this locally.

Just download a release at https://github.com/grafana/mimir and run it as `.//mimir-linux-amd64 --config.file=./mimir.yml`

The config contains:
```yaml
# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 9009
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1
```

When you uncomment the force flush I seem to get this error:

```go
package main

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
	api "go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/sdk/metric"
)

func main() {
	ctx := context.Background()

	exp, err := otlpmetrichttp.New(ctx, otlpmetrichttp.WithEndpointURL("http://localhost:9009/otlp/v1/metrics"))
	if err != nil {
		panic(err)
	}

	meterProvider := metric.NewMeterProvider(metric.WithReader(metric.NewPeriodicReader(exp)))

	otel.SetMeterProvider(meterProvider)

	meter := meterProvider.Meter("benchSyncViews")
	opt := api.WithAttributes(
		attribute.Key("test").String("2"),
		attribute.Key("job").String("otel"))
	o := []api.AddOption{opt}

	counter, err := meter.Float64UpDownCounter("t-float64-counter")
	if err != nil {
		panic(err)
	}

	fmt.Println("start")

	// if err := meterProvider.ForceFlush(context.Background()); err != nil {
	// 	panic(err)
	// }

	//add metrics
	counter.Add(ctx, 1.0, o...)

	if err := meterProvider.Shutdown(ctx); err != nil {
		panic(err)
	}
}
```
