### ISSUE TITLE
Attempt to use otel-collector 

### ISSUE THREAD

**Issue by gianarb** [open-telemetry/opentelemetry-go#533]
Hello my application successfully writes traces in the stdout but I decided to try the recently merged PR #497 but I can't get it working:

```golang
				logger.Info("Used the tracer output otel-collector")
				exp, err := otlp.NewExporter(otlp.WithInsecure())
				if err != nil {
					log.Fatalf("Failed to create the collector exporter: %v", err)
				}
				defer func() {
					_ = exp.Stop()
				}()

				tp, _ := sdktrace.NewProvider(
					sdktrace.WithConfig(sdktrace.Config{DefaultSampler: sdktrace.AlwaysSample()}),
					sdktrace.WithBatcher(exp, // add following two options to ensure flush
						sdktrace.WithScheduleDelayMillis(5),
						sdktrace.WithMaxExportBatchSize(10),
					))
				if err != nil {
					log.Fatalf("error creating trace provider: %v\n", err)
				}

				global.SetTraceProvider(tp)
```
I cloned the collector and I am using this configuration:

```yaml
receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
processors:
  batch:
  queued_retry:
exporters:
  logging:
    loglevel: debug
  jaeger_grpc:
    endpoint: "http://localhost:14250"
service:
  pipelines:
    traces:
      receivers: [opencensus]
      processors: [batch, queued_retry]
      exporters: [jaeger_grpc, logging]
```
But I do not see any log in the collector, and nothing in jaeger. I don't know what to look at at this point

any pointer?
