### ISSUE TITLE
[Metric] use Float64Counter to get wrong metric data

### ISSUE THREAD

**Issue by gunsluo** [open-telemetry/opentelemetry-go#914]
**Describe the bug**
use Float64Counter to get the wrong metric data.

the code
```
meterPusher = push.New(
			simple.NewWithExactDistribution(),
			exporter,
			push.WithPeriod(30*time.Second),
			//push.WithTimeout(10*time.Second),
		)
meterProvider = meterPusher.Provider()
meter:= meterProvider.Meter("name")

accountReadCounter : =meter.NewFloat64Counter("account.read", metric.WithDescription("record number of reading account"));

....

accountReadCounter.Add(ctx, 1)

```

the counter metric's value should not be reduced.

![image](https://user-images.githubusercontent.com/9067076/86736023-c9514d80-c065-11ea-963b-4e80950f0e53.png)

**What did you expect to see?**
the value of the counter keeps increasing by time.

**What version did you use?**
Version:  
collector 0.5.0 
otel: 0.7.0

**What config did you use?**
collector Config: 
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55679"

processors:
  batch:
  queued_retry:

extensions:
  health_check: {}

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: example
    const_labels:
      label1: test
  logging:
      loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger]

    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging]
```

**Environment**
OS:  macOS 
Compiler: go version go1.14.2 darwin/amd64

**Additional context**
it works fine on version 0.3.0(collector) and otel(0.6.0).
